image: debian/unstable
packages: 
  - golang
  - postgresql
sources:
  - https://git.sr.ht/~muirrum/hkgi
triggers:
  - action: email
    condition: always
    to: Cara Salter <cara@devcara.com>

tasks:
- build: |-
    cd hkgi
    go build
- package: |
    cd hkgi
    tar czvf hkgi.tar.gz hkgi data migrations
- deploy: |
    cd hkgi
    scp -o StrictHostKeyChecking=no hkgi.tar.gz deploy@garden.devcara.com:/opt/hkgi/hkgi-new.tar.gz
    ssh deploy@garden.devcara.com tar xzvf /opt/hkgi/hkgi-new.tar.gz -C /opt/hkgi/hkgi
    ssh deploy@garden.devcara.com /usr/bin/sudo /usr/bin/systemctl restart hkgi
